size(300,300);

pair a = (0, 0);
pair b = (0, 2);
pair c = (0, 4);
pair d = (0, 6);
pair e = (0, 8);
pair f = (0, 10);
pair g = (0, 12);
pair h = (0, 14);
pair i = (0, 16);
pair j = (0, 18);
pair k = (0, 20);
pair l = (0, 22);
pair m = (0, 24);
pair n = (0, 26);
pair p = (0, 28);
pair pos1 = (20, 3);
pair pos2 = (20, 5);
pair pos3 = (20, 7);
pair pos4 = (20, 9);
pair pos5 = (20, 11);
pair pos6 = (20, 13);
pair pos7 = (20, 15);
pair pos8 = (20, 17);
pair pos9 = (20, 19);
pair pos10 = (20, 21);
pair pos11 = (20, 23);

dot("a",a, red);
dot("b",b, red);
dot("c",c, red);
dot("d",d, red);
dot("e",e, red);
dot("f",f, red);
dot("g",g, red);
dot("h",h, red);
dot("i",i, red);
dot("j",j, red);
dot("k",k, red);
dot("l",l, red);
dot("m",m, red);
dot("n",n, red);
dot("p",p, red);
dot("1",pos1, red);
dot("2",pos2, red);
dot("3",pos3, red);
dot("4",pos4, red);
dot("5",pos5, red);
dot("6",pos6, red);
dot("7",pos7, red);
dot("8",pos8, red);
dot("9",pos9, red);
dot("10",pos10, red);
dot("11",pos11, red);

draw(a--pos2, blue);
draw(a--pos8, blue);
draw(c--pos2, blue);
draw(c--pos3, blue);
draw(b--pos1, blue);
draw(b--pos5, blue);
draw(b--pos7, blue);
draw(e--pos3, blue);
draw(e--pos8, blue);
draw(d--pos1, blue);
draw(d--pos4, blue);
draw(d--pos5, blue);
draw(d--pos6, blue);
draw(d--pos7, blue);
draw(g--pos3, blue);
draw(g--pos8, blue);
draw(g--pos11, blue);
draw(f--pos10, blue);
draw(f--pos11, blue);
draw(i--pos8, blue);
draw(i--pos9, blue);
draw(i--pos10, blue);
draw(h--pos2, blue);
draw(h--pos4, blue);
draw(h--pos9, blue);
draw(k--pos8, blue);
draw(k--pos9, blue);
draw(j--pos1, blue);
draw(j--pos5, blue);
draw(j--pos6, blue);
draw(j--pos7, blue);
draw(m--pos1, blue);
draw(m--pos4, blue);
draw(m--pos6, blue);
draw(m--pos7, blue);
draw(l--pos3, blue);
draw(l--pos9, blue);
draw(l--pos11, blue);
draw(p--pos9, blue);
draw(p--pos10, blue);
